### ISSUE TITLE
Homework 1 - Feedback

### ISSUE THREAD

**Issue by Kenneffy** [JasonMartocci/Portfolio#1]
Great job doing the homework, good indentation and very readable code. Just one tip that may be useful to you, in your CSS file it would be helpful if you had your code commented so that you organize the file in sections such as "fonts", "colors", "body elements" and etc. This is not necessary but its great for you to keep tabs so when you go back to the files you'll immediately be reminded of what a certain piece of code does.

**Comment by JasonMartocci** [comment]
Thank you for the feedback I will start adding in the comments with the responsive site.
