### ISSUE TITLE
Feedback - Week 2 Assignment

### ISSUE THREAD

**Issue by ntuvera** [JasonMartocci/Portfolio#3]
Hey @JasonMartocci, I cloned your repo and started poking around.

I opened the ```index.html``` and started resizing on the fly.  Per the homework instructions it said to match the layout for those specific pixel widths, which you nailed.  What if I asked you to make it responsive to all the possible sizes?  I can see that at specific "break" points, but within those your elements do not play nicely below specific the screen width.  I can see that you've given some very specific dimensions to images and other attributes, which will make the layout match, but not compltely scalable.  

Looking through you css, I appreciate the comments btw, it appears there are some instances of your css not being very D.R.Y.  for example
```
h1{
	font-family: "Georgia", "Times", "Times New Roman", "serif";
	color: #ffffff;
	font-size:30px;
}
h2{
	font-family: "Georgia", "Times", "Times New Roman", "serif";
	color: #4aaaa5;
	font-size:25px;
	font-weight: bold;
}
h3{
	font-family: "Georgia", "Times", "Times New Roman", "serif";
	color: #4aaaa5;
	font-size:22px;
}
```
could be condensed down by combinind selectors and then writing one line of change specifically for the element via 
```
h1, h2, h3 { 
  [shared properties] 
}

h1 {
  [unique property];
}
h2 {
  [unique property]
} 

```

Give it another go and refactor as much as you can to keep your code DRY.  I can take a look at it if you want, but that's up to you.  Also are you really comfortable with all those ```<divs>```?  If you are more power to you and your organizational skills, but without inspecting each element It _looks_ like you may not need all those ```<divs>```, ie ```content_container > left_content_container > left_content```.  If they are all absolutely necessary to the functionality of your design, then awesome.  But I think it may be possible to refactor down again.

Overall, great work.  You did exactly what we asked, so take the extra step to tweak and fine tune the design and the code.

**Comment by JasonMartocci** [comment]
Thank you for the feedback its all great. I reviewed the code and did some changes to it, not much. I tried to use less div's in my newer portfolio using bootstrap and also the games I just created. I will continue to reference back to this to make changes when i have free time.
